docker: py311-250122: initial jenkins build, raven nbs, 2 nbs failure, existing causes
This one already exist since previous build so nothing new.
  ____ RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3 ____
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # We will add a wrapper to ensure that the following operations will preserve the original data attributes, such as units and variable names.
  with xr.set_options(keep_attrs=True):
      ERA5_reference = subset.subset_shape(
          ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
      )
      ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
      ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
      ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
      ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  ERA5_pr

  Traceback:

  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Cell In[1], line 7
        3 ERA5_reference = subset.subset_shape(
        4     ds.sel(time=slice(reference_start_day, reference_stop_day)), basin_contour
        5 )
        6 ERA5_tas = ERA5_reference["t2m"].resample(time="1D")
  ----> 7 ERA5_tmin = ERA5_tas.min().chunk(-1, -1, -1)
        8 ERA5_tmax = ERA5_tas.max().chunk(-1, -1, -1)
        9 ERA5_pr = ERA5_reference["tp"].resample(time="1D").sum().chunk(-1, -1, -1)

  TypeError: DataArray.chunk() takes from 1 to 2 positional arguments but 4 were given

This one also happen in production so nothing new.
  _ RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 3 _
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # Date of the hindcast
  hdate = dt.datetime(2018, 7, 1)

  # Duration of the hindcast, in days
  duration = 7

  # Build a new model config:
  # Model configuration
  model_config_ESP = emulators.GR4JCN(
      params=[0.529, -3.396, 407.29, 1.072, 16.9, 0.947],
      Gauge=[
          rc.Gauge.from_nc(
              ts, data_type=data_type, alt_names=alt_names, data_kwds=data_kwds
          )
      ],
      HRUs=[hru],
      StartDate=hdate,
      Duration=duration,
      RunName="ESP_vs_NWP_ESPfcst",
  )

  # Set the initial states of this new config to the correct values, i.e. the end of the previous forecast.
  model_config_ESP = model_config_ESP.set_solution(hotstart)

  # Simulate the climatological ESP:
  ESP_sims = forecasting.climatology_esp(config=model_config_ESP)

  # Show the results in an xarray dataset, ready to use:
  ESP_sims.hydrograph

  Traceback:

  ---------------------------------------------------------------------------
  NameError                                 Traceback (most recent call last)
  Cell In[1], line 9
        5 duration = 7
        7 # Build a new model config:
        8 # Model configuration
  ----> 9 model_config_ESP = emulators.GR4JCN(
       10     params=[0.529, -3.396, 407.29, 1.072, 16.9, 0.947],
       11     Gauge=[
       12         rc.Gauge.from_nc(
       13             ts, data_type=data_type, alt_names=alt_names, data_kwds=data_kwds
       14         )
       15     ],
       16     HRUs=[hru],
       17     StartDate=hdate,
       18     Duration=duration,
       19     RunName="ESP_vs_NWP_ESPfcst",
       20 )
       22 # Set the initial states of this new config to the correct values, i.e. the end of the previous forecast.
       23 model_config_ESP = model_config_ESP.set_solution(hotstart)

  NameError: name 'emulators' is not defined

HydroShare_integration.ipynb known to not pass long time ago.

  =========================== short test summary info ============================
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 3
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 4
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 5
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 6
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 7
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 8
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 9
  FAILED RavenPy-master/docs/notebooks/03_Extracting_forcing_data.ipynb::Cell 10
  FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 3
  FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 4
  FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 5
  FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 6
  FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 7
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 0
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 1
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 2
  FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 3
  ================== 17 failed, 224 passed in 949.59s (0:15:49) ==================