docker: py311-250130: initial jenkins build, raven nbs, 1 nb failure, existing causes
HydroShare_integration.ipynb known to not work.

Comparing_hindcasts_and_ESP_forecasts.ipynb same error as in production.

=========================== short test summary info ============================
FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 3
FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 4
FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 5
FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 6
FAILED RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 7
FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 0
FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 1
FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 2
FAILED RavenPy-master/docs/notebooks/HydroShare_integration.ipynb::Cell 3
================== 9 failed, 232 passed in 1266.88s (0:21:06) ==================

  _ RavenPy-master/docs/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb::Cell 3 _
  Notebook cell execution failed
  Cell 3: Cell execution caused an exception

  Input:
  # Date of the hindcast
  hdate = dt.datetime(2018, 7, 1)

  # Duration of the hindcast, in days
  duration = 7

  # Build a new model config:
  # Model configuration
  model_config_ESP = emulators.GR4JCN(
      params=[0.529, -3.396, 407.29, 1.072, 16.9, 0.947],
      Gauge=[
          rc.Gauge.from_nc(
              ts, data_type=data_type, alt_names=alt_names, data_kwds=data_kwds
          )
      ],
      HRUs=[hru],
      StartDate=hdate,
      Duration=duration,
      RunName="ESP_vs_NWP_ESPfcst",
  )

  # Set the initial states of this new config to the correct values, i.e. the end of the previous forecast.
  model_config_ESP = model_config_ESP.set_solution(hotstart)

  # Simulate the climatological ESP:
  ESP_sims = forecasting.climatology_esp(config=model_config_ESP)

  # Show the results in an xarray dataset, ready to use:
  ESP_sims.hydrograph

  Traceback:

  ---------------------------------------------------------------------------
  NameError                                 Traceback (most recent call last)
  Cell In[1], line 9
        5 duration = 7
        7 # Build a new model config:
        8 # Model configuration
  ----> 9 model_config_ESP = emulators.GR4JCN(
       10     params=[0.529, -3.396, 407.29, 1.072, 16.9, 0.947],
       11     Gauge=[
       12         rc.Gauge.from_nc(
       13             ts, data_type=data_type, alt_names=alt_names, data_kwds=data_kwds
       14         )
       15     ],
       16     HRUs=[hru],
       17     StartDate=hdate,
       18     Duration=duration,
       19     RunName="ESP_vs_NWP_ESPfcst",
       20 )
       22 # Set the initial states of this new config to the correct values, i.e. the end of the previous forecast.
       23 model_config_ESP = model_config_ESP.set_solution(hotstart)

  NameError: name 'emulators' is not defined