docker: py311-250122: initial jenkins build, default nbs, 6 nbs failure, seems same cause
AttributeError: module 'dask.dataframe.core' has no attribute 'DataFrame'

  =========================== short test summary info ============================
  FAILED pavics-sdi-master/docs/source/notebooks/CaSR_basic.ipynb::Cell 1
  FAILED pavics-sdi-master/docs/source/notebooks/climex.ipynb::Cell 0
  FAILED pavics-sdi-master/docs/source/notebooks/subset-user-input.ipynb::Cell 24
  FAILED PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-3Climate-Indicators.ipynb::Cell 0
  FAILED PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-5Visualization.ipynb::Cell 3
  FAILED PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-5Visualization.ipynb::Cell 4
  FAILED PAVICS-landing-master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-6Regridding_Conversion.ipynb::Cell 1
  = 7 failed, 240 passed, 1 skipped, 5 xfailed, 1 warning in 3555.65s (0:59:15) ==